src/Entity/CvInfoDeux.php
<?php

namespace App\Entity;

use App\Repository\CvInfoDeuxRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CvInfoDeuxRepository::class)]
class CvInfoDeux
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Prenom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $profession = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $photopersonne = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $ville = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pays = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $telephone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $liensite = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $langueune = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $niveaulangueune = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $languedeux = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $niveaulanguedeux = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $competenceune = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $competencdeux = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $competencetrois = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $competencequatre = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $cdun = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $cddeux = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $cdtrois = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $NomMetierUn = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $PossitionMetierUn = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $CommentaireMetierUn = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $CommentaireMetierDeux = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $CommentaireMetierTrois = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $CommentaireMetierQuatre = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $NomMetierDeux = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $PossitionMetierDeux = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $CommentaireMetierUnn = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $CommentaireMetierDeuxx = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $CommentaireMetierTroiss = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $CommentaireMetierQuatree = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $NomFormationUne = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $PositionFormationUne = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $NomFormationDeux = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $PositionFormationDeux = null;

    #[ORM\ManyToOne(inversedBy: 'cvInfoDeuxes')]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(?string $Prenom): static
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(?string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getProfession(): ?string
    {
        return $this->profession;
    }

    public function setProfession(?string $profession): static
    {
        $this->profession = $profession;

        return $this;
    }

    public function getPhotopersonne(): ?string
    {
        return $this->photopersonne;
    }

    public function setPhotopersonne(?string $photopersonne): static
    {
        $this->photopersonne = $photopersonne;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(?string $pays): static
    {
        $this->pays = $pays;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getLiensite(): ?string
    {
        return $this->liensite;
    }

    public function setLiensite(?string $liensite): static
    {
        $this->liensite = $liensite;

        return $this;
    }

    public function getLangueune(): ?string
    {
        return $this->langueune;
    }

    public function setLangueune(?string $langueune): static
    {
        $this->langueune = $langueune;

        return $this;
    }

    public function getNiveaulangueune(): ?string
    {
        return $this->niveaulangueune;
    }

    public function setNiveaulangueune(?string $niveaulangueune): static
    {
        $this->niveaulangueune = $niveaulangueune;

        return $this;
    }

    public function getLanguedeux(): ?string
    {
        return $this->languedeux;
    }

    public function setLanguedeux(?string $languedeux): static
    {
        $this->languedeux = $languedeux;

        return $this;
    }

    public function getNiveaulanguedeux(): ?string
    {
        return $this->niveaulanguedeux;
    }

    public function setNiveaulanguedeux(?string $niveaulanguedeux): static
    {
        $this->niveaulanguedeux = $niveaulanguedeux;

        return $this;
    }

    public function getCompetenceune(): ?string
    {
        return $this->competenceune;
    }

    public function setCompetenceune(?string $competenceune): static
    {
        $this->competenceune = $competenceune;

        return $this;
    }

    public function getCompetencdeux(): ?string
    {
        return $this->competencdeux;
    }

    public function setCompetencdeux(?string $competencdeux): static
    {
        $this->competencdeux = $competencdeux;

        return $this;
    }

    public function getCompetencetrois(): ?string
    {
        return $this->competencetrois;
    }

    public function setCompetencetrois(?string $competencetrois): static
    {
        $this->competencetrois = $competencetrois;

        return $this;
    }

    public function getCompetencequatre(): ?string
    {
        return $this->competencequatre;
    }

    public function setCompetencequatre(?string $competencequatre): static
    {
        $this->competencequatre = $competencequatre;

        return $this;
    }

    public function getCdun(): ?string
    {
        return $this->cdun;
    }

    public function setCdun(?string $cdun): static
    {
        $this->cdun = $cdun;

        return $this;
    }

    public function getCddeux(): ?string
    {
        return $this->cddeux;
    }

    public function setCddeux(?string $cddeux): static
    {
        $this->cddeux = $cddeux;

        return $this;
    }

    public function getCdtrois(): ?string
    {
        return $this->cdtrois;
    }

    public function setCdtrois(?string $cdtrois): static
    {
        $this->cdtrois = $cdtrois;

        return $this;
    }

    public function getNomMetierUn(): ?string
    {
        return $this->NomMetierUn;
    }

    public function setNomMetierUn(?string $NomMetierUn): static
    {
        $this->NomMetierUn = $NomMetierUn;

        return $this;
    }

    public function getPossitionMetierUn(): ?string
    {
        return $this->PossitionMetierUn;
    }

    public function setPossitionMetierUn(?string $PossitionMetierUn): static
    {
        $this->PossitionMetierUn = $PossitionMetierUn;

        return $this;
    }

    public function getCommentaireMetierUn(): ?string
    {
        return $this->CommentaireMetierUn;
    }

    public function setCommentaireMetierUn(?string $CommentaireMetierUn): static
    {
        $this->CommentaireMetierUn = $CommentaireMetierUn;

        return $this;
    }

    public function getCommentaireMetierDeux(): ?string
    {
        return $this->CommentaireMetierDeux;
    }

    public function setCommentaireMetierDeux(?string $CommentaireMetierDeux): static
    {
        $this->CommentaireMetierDeux = $CommentaireMetierDeux;

        return $this;
    }

    public function getCommentaireMetierTrois(): ?string
    {
        return $this->CommentaireMetierTrois;
    }

    public function setCommentaireMetierTrois(?string $CommentaireMetierTrois): static
    {
        $this->CommentaireMetierTrois = $CommentaireMetierTrois;

        return $this;
    }

    public function getCommentaireMetierQuatre(): ?string
    {
        return $this->CommentaireMetierQuatre;
    }

    public function setCommentaireMetierQuatre(?string $CommentaireMetierQuatre): static
    {
        $this->CommentaireMetierQuatre = $CommentaireMetierQuatre;

        return $this;
    }

templates/immobilier/immobilier_form/form_cv_1.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formulaire de génération de Cv Immobilier{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    <link rel="stylesheet" href="{{ asset('css/Cv_Form_Dev4.css') }}">
{% endblock %}

{% block body %}
{{ form_start(form) }}
    <div class="BackgroundOrange">
        <div class="container-fluid m-0 p-0">
            <div class="row g-0">
                <div class="col" style="width: 13%; max-width: 13%;">
                    <div class="BackgroundBleu">
                        <h1 class="TexteImport">Importer votre photo</h1>
                        <div class="photo-upload">
                            <label for="photo-upload-input">
                                <img id="photo-placeholder" src="{{ asset('assets/PhotoCv.png') }}" alt="Téléchargez une photo" class="photo-placeholder" style="cursor: pointer;">
                            </label>
                            {{ form_widget(form.photopersonne, {'id': 'photo-upload-input', 'style': 'display: none;'}) }}
                            <button type="button" id="reset-photo" class="BoutonRetirer">Retirer la photo</button>
                            <div class="image-advice">
                                <p>Conseil : pour un rendu optimal, nous vous recommandons d'utiliser une image au format PNG ou JPG avec une dimension de <strong>360 x 360 pixels</strong>. Vous pouvez redimensionner facilement votre image sur <a class="LienDecorationWhite" href="https://imageresizer.com/" target="_blank">Image Resizer</a>.</p>
                                <p>Si vous souhaitez arrondir votre image, vous pouvez le faire en quelques clics avec <a class="LienDecorationWhite" href="https://www.rounder.com" target="_blank">Rounder</a> ou un autre outil similaire.</p>
                            </div>
                        </div>
                        <h1 class="textcv">Cv en cours de création</h1>
                        <img class="cv" src="{{ asset('assets/CvImmobilier/1.png') }}">
                    </div>
                </div>

                <div class="col" style="width: 87%; max-width: 87%;">
                    <div class="container">
                        <div class="row">
                            <div class="col-12 form">
                                <h1 class="TitreUn">Génération du Cv Immobilier 0-10 ans</h1><br>
                                <p class="InfoForm">Veuillez remplir le formulaire ci-dessous pour générer votre CV avec vos informations.</p>
                            </div>
                        </div>
                    </div><br><br>

                    <div class="form">
                        <div class="container">
                            <div class="row">
                                <h1 class="InfoInput">Information personnelle</h1>
                                <div class="col-6">
                                    {{ form_row(form.Nom, {'label': false, 'attr': {'class': 'InputForm', 'placeholder': 'Nom :'}}) }}
                                </div>
                                <div class="col-6">
                                    {{ form_row(form.prenom, {'label': false, 'attr': {'class': 'InputForm', 'placeholder': 'Prénom :'}}) }}
                                </div>
                                <div class="col-6">
                                    {{ form_row(form.age, {'label': false, 'attr': {'class': 'InputForm', 'placeholder': 'Âge :'}}) }}
                                </div>
                                <div class="col-6">
                                    {{ form_row(form.permis, {'label': false, 'attr': {'class': 'InputForm', 'placeholder': 'Permis de conduire :'}}) }}
                                </div>
                            </div>
                        </div><br>

                        <div class="container">
                            <div class="row">
                                <h1 class="InfoInput">Coordonnées</h1>
                                <div class="col-6">
                                    {{ form_row(form.adresse, {'label': false, 'attr': {'class': 'InputForm', 'placeholder': 'Adresse :'}}) }}
                                </div>
                                <div class="col-6">
                                    {{ form_row(form.email, {'label': false, 'attr': {'class': 'InputForm', 'placeholder': 'Adresse email :'}}) }}
                                </div>
                                <div class="col-6">
                                    {{ form_row(form.telephone, {'label': false, 'attr': {'class': 'InputForm', 'placeholder': 'Téléphone :'}}) }}
                                </div>
                                <div class="col-6">
                                    {{ form_row(form.NomMetier, {'label': false, 'attr': {'class': 'InputForm', 'placeholder': 'Poste actuel :'}}) }}
                                </div>
                            </div>
                        </div><br>

                        <div class="container">
                            <div class="row">
                                <h1 class="InfoInput">Formations</h1>
                                <div class="col-6">
                                    {{ form_row(form.FormationUne, {'label': false, 'attr': {'class': 'InputFormm', 'placeholder': 'Nom de la formation 1 :'}}) }}
                                </div>
                                <div class="col-6">
                                    {{ form_row(form.FormationDeux, {'label': false, 'attr': {'class': 'InputFormm', 'placeholder': 'Nom de la formation 2 :'}}) }}
                                </div>
                                <div class="col-6">
                                    {{ form_row(form.FormationTrois, {'label': false, 'attr': {'class': 'InputFormm', 'placeholder': 'Nom de la formation 3 :'}}) }}
                                </div>
                            </div>
                        </div><br>

                        <div class="container">
                            <div class="row">
                                <h1 class="InfoInput">Compétences</h1>
                                <div class="col-6">
                                    {{ form_row(form.CompetenceUne, {'label': false, 'attr': {'class': 'InputFormm', 'placeholder': 'Compétence 1 :'}}) }}
                                </div>
                                <div class="col-6">
                                    {{ form_row(form.CompetenceDeux, {'label': false, 'attr': {'class': 'InputFormm', 'placeholder': 'Compétence 2 :'}}) }}
                                </div>
                                <div class="col-6">
                                    {{ form_row(form.CompetenceTrois, {'label': false, 'attr': {'class': 'InputFormm', 'placeholder': 'Compétence 3 :'}}) }}
                                </div>
                                <div class="col-6">
                                    {{ form_row(form.CompetenceQuatre, {'label': false, 'attr': {'class': 'InputFormm', 'placeholder': 'Compétence 4 :'}}) }}
                                </div>
                                <div class="col-6">
                                    {{ form_row(form.CompetenceCinq, {'label': false, 'attr': {'class': 'InputFormm', 'placeholder': 'Compétence 5 :'}}) }}
                                </div>
                                <div class="col-6">
                                    {{ form_row(form.Competencesix, {'label': false, 'attr': {'class': 'InputFormm', 'placeholder': 'Compétence 6 :'}}) }}
                                </div>
                            </div>
                        </div><br>

                        <div class="container">
                            <div class="row">
                                <h1 class="InfoInput">Expériences professionnelles</h1>
                                <div class="col-6">
                                    {{ form_row(form.ExperienceUne, {'label': false, 'attr': {'class': 'InputFormm', 'placeholder': 'Nom du poste 1 :'}}) }}
                                </div>
                                <div class="col-6">
                                    {{ form_row(form.ExperienceDeux, {'label': false, 'attr': {'class': 'InputFormm', 'placeholder': 'Nom du poste 2 :'}}) }}
                                </div>
                                <div class="col-6">
                                    {{ form_row(form.ExperienceTrois, {'label': false, 'attr': {'class': 'InputFormm', 'placeholder': 'Nom du poste 3 :'}}) }}
                                </div>
                            </div>
                        </div><br>

                        <div class="container">
                            <div class="row">
                                <h1 class="InfoInput">Langues</h1>
                                <div class="col-6">
                                    {{ form_row(form.LangueUne, {'label': false, 'attr': {'class': 'InputForm', 'placeholder': 'Langue 1 :'}}) }}
                                </div>
                                <div class="col-6">
                                    {{ form_row(form.NiveauLangueUne, {'label': false, 'attr': {'class': 'InputForm', 'placeholder': 'Niveau de la langue 1 :'}}) }}
                                </div>
                                <div class="col-6">
                                    {{ form_row(form.LangueDeux, {'label': false, 'attr': {'class': 'InputForm', 'placeholder': 'Langue 2 :'}}) }}
                                </div>
                                <div class="col-6">
                                    {{ form_row(form.NiveauLangueDeux, {'label': false, 'attr': {'class': 'InputForm', 'placeholder': 'Niveau de la langue 2 :'}}) }}
                                </div>
                                <div class="col-6">
                                    {{ form_row(form.LangueTrois, {'label': false, 'attr': {'class': 'InputForm', 'placeholder': 'Langue 3 :'}}) }}
                                </div>
                                <div class="col-6">
                                    {{ form_row(form.NiveauLangueTrois, {'label': false, 'attr': {'class': 'InputForm', 'placeholder': 'Niveau de la langue 3 :'}}) }}
                                </div>
                            </div>
                        </div><br>

                        <div class="container">
                            <div class="row">
                                <h1 class="InfoInput">Loisirs</h1>
                                <div class="col-6">
                                    {{ form_row(form.LoisirUn, {'label': false, 'attr': {'class': 'InputForm', 'placeholder': 'Loisir 1 :'}}) }}
                                </div>
                                <div class="col-6">
                                    {{ form_row(form.LoisirDeux, {'label': false, 'attr': {'class': 'InputForm', 'placeholder': 'Loisir 2 :'}}) }}
                                </div>
                                <div class="col-6">
                                    {{ form_row(form.LoisirTrois, {'label': false, 'attr': {'class': 'InputForm', 'placeholder': 'Loisir 3 :'}}) }}
                                </div>
                                <div class="col-6">
                                    {{ form_row(form.LoisirQuatre, {'label': false, 'attr': {'class': 'InputForm', 'placeholder': 'Loisir 4 :'}}) }}
                                </div>
                            </div>
                        </div><br>

                        <div class="container">
                            <div class="row">
                                <div class="col-12">
                                    {{ form_row(form.valider, {'label': 'Générer votre CV', 'attr': {'class': 'BoutonGenerer'}}) }}
                                </div>
                            </div>
                        </div><br>
                    </div>
                </div>
            </div>
        </div>
    </div>
{{ form_end(form) }}
{% endblock %}

{% block javascripts %}
<script>
document.addEventListener("DOMContentLoaded", function() {
    const photoUploadInput = document.getElementById('photo-upload-input');
    const photoPlaceholder = document.getElementById('photo-placeholder');
    const resetPhotoButton = document.getElementById('reset-photo');

    if (photoUploadInput && photoPlaceholder) {
        photoPlaceholder.addEventListener('mousedown', function(event) {
            event.preventDefault();
            photoUploadInput.click();
        });

        photoUploadInput.addEventListener('change', function(event) {
            const file = event.target.files[0];
            if (file) {
                const reader = new FileReader();
                reader.onload = function(e) {
                    photoPlaceholder.src = e.target.result;
                };
                reader.readAsDataURL(file);
            }
        });
    } else {
        console.error("L'un des éléments n'a pas été trouvé dans le DOM.");
    }

    if (resetPhotoButton && photoPlaceholder) {
        resetPhotoButton.addEventListener('click', function() {
            photoPlaceholder.src = "{{ asset('assets/PhotoCv.png') }}";
            photoUploadInput.value = "";
        });
    }
});
</script>
{% endblock %}